name: CI

on: [push]

jobs:
  build:
    runs-on: [macOS-10.14]
    steps:
    - uses: actions/checkout@v1
    - name: Install docker
      run: brew install bash-completion && brew cask install docker && brew install kubectl && brew cask install minikube
    - name: Check docker
      run: docker version && docker-compose version && docker-machine --version && kubectl version --client
